#!/bin/bash

rm -rf $1.app
mkdir -p $1.app/Contents/MacOS
ln -s `pwd`/$1 $1.app/Contents/MacOS
cat >$1.app/Contents/Info.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>$1</string>
</dict>
</plist>
EOF
